### ISSUE TITLE
Missing closedAt in gql query

### ISSUE THREAD

**Issue by Sam-Lin-MillersLab** [gr2m/github-project#107]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/gr2m/github-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Please select the environment(s) that are relevant to your bug report

- [ ] Browsers
- [X] Node
- [ ] Deno

### Versions

Version : 3.3.2

### What happened?

I think we missed closedAt in this query 

https://github.com/gr2m/github-project/blob/a129089bc142b54d6ecb864ae2c76d5921e23333/api/lib/queries.js#L23

### Would you be interested in contributing a fix?

- [X] yes

**Comment by gr2m** [comment]
done via https://github.com/gr2m/github-project/pull/108
