### ISSUE TITLE
milestone in IssueContent should be nullable  

### ISSUE THREAD

**Issue by maxisam** [gr2m/github-project#110]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/gr2m/github-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Please select the environment(s) that are relevant to your bug report

- [ ] Browsers
- [X] Node
- [ ] Deno

### Versions

3.3.3.

### What happened?

https://github.com/gr2m/github-project/blob/1b1156dc805bcdb319e930bd366a44b0f805f01f/index.d.ts#L217

milestone should be nullable

### Would you be interested in contributing a fix?

- [X] yes

**Comment by gr2m** [comment]
done via #111
