### ISSUE TITLE
v3.3.5 breaking change

### ISSUE THREAD

**Issue by abraham** [gr2m/github-project#125]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/gr2m/github-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Please select the environment(s) that are relevant to your bug report

- [ ] Browsers
- [X] Node
- [ ] Deno

### Versions

v3.3.5

### What happened?

Upgrade from [v3.3.4 to v3.3.5](https://github.com/gr2m/github-project/compare/v3.3.4...v3.3.5) in a node16 environment. I expect `github-project` to keep working but `octokit/app` [drops support for node 14 & 16](https://github.com/octokit/app.js/releases/tag/v14.0.0) among other breaking changes.

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by gr2m** [comment]
our tests still pass so we should be fine. But I'll revert it anyway just to avoid future surprises and release a breaking change that drops node 16 as well
