### ISSUE TITLE
Throw helpful error when project for given number cannot be found

### ISSUE THREAD

**Issue by gr2m** [gr2m/github-project#35]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/gr2m/github-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Please select the environment(s) that are relevant to your bug report

- [X] Browsers
- [X] Node
- [X] Deno

### Versions

1.3.2

### What happened?

When running e.g. `project.items.list()` but the project cannot be found, an unhelpful error is currently thrown.

```
github-project/api/lib/get-state-with-project-items.js:32
    projectNext.fields.nodes
                ^

TypeError: Cannot read properties of null (reading 'fields')
    at getStateWithProjectItems (github-project/api/lib/get-state-with-project-items.js:32:17)
    at async listItems (github-project/api/items.list.js:13:26)
    at async updateMemex (file:///Users/gregor/code/github/how-we-work-booster-pack/scripts/update-memex.js:88:17)
    at async run (file:///Users/gregor/code/github/how-we-work-booster-pack/scripts/update-memex.js:62:5)
```

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by RohithSurya** [comment]
Hi @gr2m, I would like to work on the issue.

I reviewed the code and added a try/catch block when accessing the project.

I changed the listitems function for error handling:
<img width="886" alt="Screenshot 2023-09-30 at 7 24 54 PM" src="https://github.com/gr2m/github-project/assets/29703054/15cc7179-7127-4a84-bdb8-92aa7ebc4edd">

This would fix the issue, I believe. 
Can I get your thoughts on this too? 😊

**Comment by gr2m** [comment]
Code looks good, but instead of instantiating `GitHubProjectError`, I would create a new error class specific to this error, like we do for other errors as well.

**Comment by gr2m** [comment]
hey sorry I needed this fixed and totally forgot that you were working on it :( It's done via 

- #138 

Would you maybe like to work on any of the other open issues with a https://github.com/gr2m/github-project/labels/Pull%20Request%20welcome label? I'd happy to give you guidance.

Really sorry about this!
