### ISSUE TITLE
Update detection of draft issues

### ISSUE THREAD

**Issue by gr2m** [gr2m/github-project#36]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/gr2m/github-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Please select the environment(s) that are relevant to your bug report

- [X] Browsers
- [X] Node
- [X] Deno

### Versions

1.3.2

### What happened?

In `node_modules/github-project/api/lib/project-item-node-to-github-project-item.js`, we currently have this check to identify draft items

```js
  // item is draft
  if (!itemNode.content) {
    return {
      id: itemNode.id,
      fields,
      isDraft: true,
    };
  }
```

however, it looks like GitHub changed the API response, `itemNode.content` is now present, which leads to this error

```
/github-project/api/lib/project-item-node-to-github-project-item.js:36
    assignees: itemNode.content.assignees.nodes.map((node) => node.login),
                                          ^

TypeError: Cannot read properties of undefined (reading 'nodes')
    at projectItemNodeToGitHubProjectItem (/github-project/api/lib/project-item-node-to-github-project-item.js:36:43)
    at /github-project/api/lib/get-state-with-project-items.js:37:12
    at Array.map (<anonymous>)
    at getStateWithProjectItems (/github-project/api/lib/get-state-with-project-items.js:35:41)
    at async listItems (/github-project/api/items.list.js:13:26)
    at async updateMemex (file:///Users/gregor/code/github/how-we-work-booster-pack/scripts/update-memex.js:88:17)
    at async run (file:///Users/gregor/code/github/how-we-work-booster-pack/scripts/update-memex.js:62:5)
```

The new check needs to look like this

```js
  // item is draft
  if (!itemNode.content || itemNode.content.__typename === 'DraftIssue') {
    return {
      id: itemNode.id,
      fields,
      isDraft: true,
    };
  }
```

We can probably remove `!itemNode.content` now, but should verify that it works in all circumstances

### Would you be interested in contributing a fix?

- [X] yes

**Comment by mikesurowiec** [comment]
Forgot to include the issue in the PR https://github.com/gr2m/github-project/pull/38
