### ISSUE TITLE
Add `databaseId` to `projectItem.content`

### ISSUE THREAD

**Issue by mikesurowiec** [gr2m/github-project#60]
### Please avoid duplicates

- [X] I checked [all open feature requests](https://github.com/gr2m/github-project/issues?q=is%3Aissue+is%3Aopen+label%3Afeature) and none of them matched my problem.

### What’s missing?

The `owner` is missing on `projectItem.content`.

### Why?

It would be nice to include because projectItems are passed around and the owner (along with repo, which already exists) is required to query for additional information about that item (e.g. fetch comments from an issue).

### Alternatives you tried

functions that pass additional arguments alongside the projectItem

### Would you be interested in contributing the feature?

- [X] yes

**Comment by gr2m** [comment]
couldn't you use `project.org` for that? I _think_ `projectItem.content` is currently 1:1 what we get from the GraphQL result, I'd prefer not to alter it

**Comment by mikesurowiec** [comment]
> couldn't you use project.org for that? I think projectItem.content is currently 1:1 what we get from the GraphQL result, I'd prefer not to alter it

The information is available via other means, but it's not particularly ergonomic to access.

For example, we have a handful of function that attempt to operate on a single projectItem, but they currently require an additional owner parameter. It feels like it should be accessible via the item (since we know the item must have been fetched with a known owner). Propagating the owner to the individual items means we won't need to pass around / mock the larger project for smaller utility functions.

```ts
function loadComments(projectItem: GitHubProjectItem) {
    const { data } = await octokit.rest.issues.listComments({
      owner: projectItem.owner, // can't currently do this
      repo: projectItem.content.repository,
      issue_number: projectItem.content.number,
    });
}   
```

Adding it to `projectItem` rather than to `projectItem.content` would be perfectly acceptable as well. The "odd" feeling is that the projectItem is one parameter short from having all information necessary to access other aspects of itself via the API.

**Comment by gr2m** [comment]
How about we add `databaseId` to `GitHubProjectItem`. Once you have the database ID, you can do this

```
await octokit.request("GET /repositories/{repository_id}/issues/{issue_number}/comments", {
  repository_id: projectItem.content.databaseId,
  issue_number: projectItem.content.number
})
```

The `"GET /repositories/{repository_id}*" routes are not documented, but they exists since forever, and are heavily used by integrators who don't want to rely on repository names, as names can change.

I feel setting `owner` on `projectItem` or `projectItem.content` feels wrong. If at all we could set `projectItem.project` to the self-reference the project instance?

Btw, I'd recommend to use [`octokit.paginate`](https://github.com/octokit/octokit.js/#pagination) when loading issue comments, otherwise you'll only get the first 30 by default

**Comment by gr2m** [comment]
I think we are already setting `.databaseId`, but it's missing in types

**Comment by gr2m** [comment]
okay let's add `databaseId` for now, that is straight forward and something we should do anyway.
